version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/daimaxiaofeng/app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/daimaxiaofeng/app/nginx/locations:/etc/nginx/locations
      - /home/daimaxiaofeng/app/nginx/html:/usr/share/nginx/html
      - /home/daimaxiaofeng/app/nginx/cert:/usr/share/nginx/cert